services:
  - type: web
    name: poultry-farm-backend
    runtime: python
    env: production
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "poultry-farm-backend.onrender.com,poultry-farm-amasika-bce83.web.app"
      - key: DATABASE_URL
        fromDatabase:
          name: poultry-farm-db
          property: connectionString
databases:
  - name: poultry-farm-db
    plan: free